https://cli.fusio.net/cli/climate_data/webdata/dly1575.csv:
  last_modified: Sat, 14 Jun 2025 15:47:15 GMT
  etag: '"40ff9-2573db-6378a13a726c0"'
https://cli.fusio.net/cli/climate_data/webdata/dly2275.csv:
  last_modified: Sat, 14 Jun 2025 15:47:21 GMT
  etag: '"4104f-2bf521-6378a1402b440"'
https://cli.fusio.net/cli/climate_data/webdata/hly2275.csv:
  last_modified: Sat, 14 Jun 2025 15:42:06 GMT
  etag: '"40fb5-390d176-6378a013c2f80"'
